# Generated by Django 4.2.11 on 2025-06-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('prompt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_title', models.TextField(blank=True, null=True)),
                ('generated_intro', models.TextField(blank=True, null=True)),
                ('generated_style_section', models.TextField(blank=True, null=True)),
                ('generated_conclusion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255, unique=True)),
                ('ethnicity', models.CharField(blank=True, max_length=255, null=True)),
                ('skin_tone', models.CharField(blank=True, max_length=255, null=True)),
                ('hair_texture', models.CharField(blank=True, max_length=255, null=True)),
                ('face_shape', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.CharField(max_length=255, unique=True)),
                ('title_prompt', models.TextField(blank=True, null=True)),
                ('intro_prompt', models.TextField(blank=True, null=True)),
                ('style_prompt', models.TextField(blank=True, null=True)),
                ('conclusion_prompt', models.TextField(blank=True, null=True)),
                ('meta_data_prompt', models.TextField(blank=True, null=True)),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_title', models.TextField(blank=True, null=True)),
                ('generated_intro', models.TextField(blank=True, null=True)),
                ('generated_style_section', models.TextField(blank=True, null=True)),
                ('generated_conclusion', models.TextField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='WordAI_Publisher.keyword')),
                ('model_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WordAI_Publisher.modelinfo')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WordAI_Publisher.prompt')),
            ],
        ),
    ]
