# Generated by Django 4.2.11 on 2025-06-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='generated_conclusion',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='generated_image_url',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='generated_intro',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='generated_style_section',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='generated_title',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='meta_title',
        ),
    ]
