# Generated by Django 4.2.11 on 2025-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0003_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='style_images',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
