# Generated by Django 4.2.11 on 2025-06-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0004_post_style_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_generated',
            field=models.CharField(default='completed', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_status',
            field=models.CharField(choices=[('not_generated', 'Not Generated'), ('in_process', 'In Process'), ('completed', 'Completed')], default='not_generated', max_length=16),
        ),
        migrations.AddField(
            model_name='post',
            name='style_images_status',
            field=models.CharField(choices=[('not_generated', 'Not Generated'), ('in_process', 'In Process'), ('completed', 'Completed')], default='not_generated', max_length=16),
        ),
    ]
