# Generated by Django 4.2.11 on 2025-07-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0005_post_content_generated_post_featured_image_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modelinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'managed': False},
        ),
    ]
