# Generated by Django 4.2.11 on 2025-08-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0006_alter_keyword_options_alter_modelinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keyword',
            table='wordai_publisher_keyword',
        ),
        migrations.AlterModelTable(
            name='modelinfo',
            table='wordai_publisher_modelinfo',
        ),
        migrations.AlterModelTable(
            name='post',
            table='wordai_publisher_post',
        ),
        migrations.AlterModelTable(
            name='prompt',
            table='wordai_publisher_prompt',
        ),
    ]
