# Generated by Django 4.2.11 on 2025-08-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0007_alter_keyword_table_alter_modelinfo_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={},
        ),
    ]
