# Generated by Django 4.2.11 on 2025-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0008_alter_keyword_options_alter_modelinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='prompt_id',
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='build_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='expression_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='eye_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='grooming_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='hair_color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='tshirt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='wardrobe_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='wardrobe_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_prompt_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='style_image_descriptions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='style_prompts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='featured_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='master_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pushed', 'Pushed')], default='draft', max_length=20),
        ),
        migrations.AlterModelTable(
            name='keyword',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modelinfo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prompt',
            table=None,
        ),
    ]
