# Generated by Django 4.2.11 on 2025-08-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0009_remove_keyword_prompt_id_modelinfo_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modelinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'managed': False},
        ),
    ]
