# Generated by Django 4.2.11 on 2025-08-21 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WordAI_Publisher', '0010_alter_keyword_options_alter_modelinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keyword',
            table='wordai_publisher_keyword',
        ),
        migrations.AlterModelTable(
            name='modelinfo',
            table='wordai_publisher_modelinfo',
        ),
        migrations.AlterModelTable(
            name='post',
            table='wordai_publisher_post',
        ),
        migrations.AlterModelTable(
            name='prompt',
            table='wordai_publisher_prompt',
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('individual', 'individual'), ('master', 'master')], default='individual', max_length=20)),
                ('version_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], db_index=True, default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WordAI_Publisher.keyword')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WordAI_Publisher.post')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WordAI_Publisher.prompt')),
            ],
        ),
    ]
