# Generated by Django 4.2.11 on 2025-11-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0011_alter_keyword_table_alter_modelinfo_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationjob',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={},
        ),
    ]
