# Generated by Django 4.2.11 on 2025-11-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordAI_Publisher', '0012_alter_generationjob_options_alter_prompt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='daytime_outfits_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='daytime_outfits_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='destination_specific_extras_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='destination_specific_extras_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='evening_and_nightlife_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='evening_and_nightlife_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='foodlove_card_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='outdoor_activities_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='outdoor_activities_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='packing_essentials_checklist_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='packing_essentials_checklist_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='quick_style_snapshot_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='quick_style_snapshot_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='seasonal_variations_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='seasonal_variations_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='style_tips_for_blending_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='style_tips_for_blending_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='template_type',
            field=models.CharField(choices=[('regular', 'HairStyles'), ('modular', 'Modular'), ('food_love', 'Food Love')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='generationjob',
            table='wordai_publisher_generationjob',
        ),
        migrations.AlterModelTable(
            name='prompt',
            table=None,
        ),
    ]
