"""
Django settings for csvuploader project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.conf import settings
import openai
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
import requests
from django.core.files.base import ContentFile
from django.contrib import admin

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-if@cu3cz)hm1h3_qd3b)#eqat#k6vct(1fsat5(z=u#r2rmtaf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'WordAI_Publisher',  # 👈 Updated app name
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'csvuploader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'csvuploader.wsgi.application'
STATIC_URL = '/static/'

STATICFILES_DIRS = [
]

# Add this line for collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'content_automation',
        'USER': 'prd_user',
        'PASSWORD': 'mY2=bK7=eT4+mJ8+jK7-',
        'HOST': 'us-east4-001.proxy.kinsta.app',
        'PORT': '30538',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Media files (for user-uploaded/generated content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom admin site settings
ADMIN_SITE_HEADER = '<img src="https://www.fashionbeans.com/wp-content/uploads/2023/09/fashionbeans_logoss.png" alt="FashionBeans" style="height: 40px; vertical-align: middle;">'
ADMIN_SITE_TITLE = "FashionBeans Admin"
ADMIN_INDEX_TITLE = "Content Management"

OPENAI_API_KEY = "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"
WORDPRESS_API_URL_MEDIA ="https://ieghpqrlf6.wpdns.site/wp-json/wp/v2/media"
WORDPRESS_API_URL = "https://ieghpqrlf6.wpdns.site/wp-json/wp/v2/posts"
WORDPRESS_USERNAME = "Himanshu"
WORDPRESS_APPLICATION_PASSWORD = "G2zl vWlX ow81 G6IJ A6QL CN1p"
WORDPRESS_JWT_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2llZ2hwcXJsZjYud3BkbnMuc2l0ZSIsImlhdCI6MTc1MDc2MzQ5MCwibmJmIjoxNzUwNzYzNDkwLCJleHAiOjE3NTEzNjgyOTAsImRhdGEiOnsidXNlciI6eyJpZCI6Ijg2OCJ9fX0.ot9YNnk9Omk8c5T-1N6s3ForwCCGygf8WCERGyRjllo"

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'extraPlugins': 'codesnippet',
        'codeSnippet_theme': 'xcode',
    },
}


